### ISSUE TITLE
Update neo-local

### ISSUE THREAD

**Issue by DalderupMaurice** [nos/nos-local#4]
Currently the neo-local is linked to the NeoAuth version of Neo-Local. This version is old and outdated.

We should replace this submodule with the one from [CoZ](
https://github.com/CityOfZion/neo-local) - which is maintained and compatible with windows aswell

**Comment by jeroenptrs** [comment]
Yeah there's a lot this repo needs. Will come back to this ASAP!

**Comment by jeroenptrs** [comment]
Fixed through #5
